export const mockCities: string[] = [
    "Americana",
    "Anápolis",
    "Aparecida de Goiânia",
    "Aracaju",
    "Araraquara",
    "Araçatuba",
    "Bagé",
    "Barueri",
    "Bauru",
    "Belém",
    "Belo Horizonte",
    "Betim",
    "Blumenau",
    "Boa Vista",
    "Brasília",
    "Campina Grande",
    "Campinas",
    "Campo Grande",
    "Campos dos Goytacazes",
    "Canoas",
    "Carapicuíba",
    "Cariacica",
    "Caruaru",
    "Cascavel",
    "Caucaia",
    "Caxias do Sul",
    "Contagem",
    "Criciúma",
    "Cuiabá",
    "Curitiba",
    "Diadema",
    "Divinópolis",
    "Dourados",
    "Duque de Caxias",
    "Feira de Santana",
    "Florianópolis",
    "Fortaleza",
    "Foz do Iguaçu",
    "Franca",
    "Goiânia",
    "Governador Valadares",
    "Guarujá",
    "Guarulhos",
    "Ilhéus",
    "Imperatriz",
    "Ipatinga",
    "Itabuna",
    "Itaquaquecetuba",
    "Jaboatão dos Guararapes",
    "Jacareí",
    "João Pessoa",
    "Joinville",
    "Juiz de Fora",
    "Jundiaí",
    "Lages",
    "Limeira",
    "Londrina",
    "Macapá",
    "Maceió",
    "Manaus",
    "Marília",
    "Maringá",
    "Mauá",
    "Mogi das Cruzes",
    "Montes Claros",
    "Mossoró",
    "Natal",
    "Niterói",
    "Nova Friburgo",
    "Nova Iguaçu",
    "Novo Hamburgo",
    "Olinda",
    "Osasco",
    "Palmas",
    "Passo Fundo",
    "Paulista",
    "Pelotas",
    "Petrópolis",
    "Petrolina",
    "Piracicaba",
    "Ponta Grossa",
    "Porto Alegre",
    "Porto Velho",
    "Presidente Prudente",
    "Recife",
    "Ribeirão das Neves",
    "Ribeirão Preto",
    "Rio Branco",
    "Rio de Janeiro",
    "Rio Grande",
    "Salvador",
    "Santa Maria",
    "Santarém",
    "Santo André",
    "Santos",
    "São Bernardo do Campo",
    "São Gonçalo",
    "São João de Meriti",
    "São José do Rio Preto",
    "São José dos Campos",
    "São José dos Pinhais",
    "São Leopoldo",
    "São Luís",
    "São Paulo",
    "São Vicente",
    "Serra",
    "Sete Lagoas",
    "Sorocaba",
    "Sumaré",
    "Suzano",
    "Taubaté",
    "Teresina",
    "Teresópolis",
    "Uberaba",
    "Uberlândia",
    "Uruguaiana",
    "Viamão",
    "Vila Velha",
    "Vitória",
    "Vitória da Conquista",
    "Volta Redonda"
];
