export const mockCities: string[] = [
    "São Paulo",
    "Rio de Janeiro",
    "Salvador",
    "Brasília",
    "Fortaleza",
    "Belo Horizonte",
    "Manaus",
    "Curitiba",
    "Recife",
    "Porto Alegre",
    "Goiânia",
    "Belém",
    "São Luís",
    "Maceió",
    "Campo Grande",
    "Teresina",
    "João Pessoa",
    "Natal",
    "Aracaju",
    "Cuiabá",
    "Florianópolis",
    "Porto Velho",
    "Macapá",
    "Boa Vista",
    "Rio Branco",
    "Palmas",
    "Vitória",
];
